improve translation of mid of ch15-02
rust-lang-ja/book-ja pull request #149
Opened 2021-04-17 00:22 UTC by m-shaka

15-02の"Defining` Our Own Smart Pointer"からの2セクションを直しました

2021-04-17 00:28 UTC, m-shaka commented on src/ch15-02-deref.md
> +Rustが`*`演算子を`deref`メソッドの呼び出しと普通の参照外しへと置き換えてくれるので、
元の訳だと「derefの呼び出しに置き換えてから参照外しにまた置き換える」ような印象を与える。上の説明を読めばどんな置き換えかわかるので、無理にthenを訳さないことにしました

2021-04-18 06:36 UTC, tatsuya6502 requested changes
ありがとうございます。2点コメントしましたので、ご確認をお願いします。

2021-04-18 08:31 UTC, m-shaka commented on src/ch15-02-deref.md
> +`Deref`がなければ、コンパイラは`&`参照しか参照外しできなくなります。`deref`メソッドのおかげでコンパイラは、どんな型であれ`Deref`を実装していれば`deref`メソッドを呼び出して`&`参照を得ることができます。コンパイラはその参照を外す方法を知っているのです。
くどさは自分でも少し気にはなっていました。ご提案の方が読みやすいと思います！

2021-04-18 11:39 UTC, tatsuya6502 approved these changes
レビューOKですのでマージします。

おつかれさまでした！

2021-04-18 11:39 UTC, merged