ch02-00のコードと説明文をupdateしました
rust-lang-ja/book-ja pull request #181
Opened 2022-03-12 03:28 UTC by puripuri2100

2022-03-12 04:23 UTC, tatsuya6502 commented
メモ：
CircleCIジョブを起動するためのweb hookがなぜかerror 400になってしまう。（Redeliverしても同じエラー）

ローカルの環境でビルド＋レビューすることにする。

![book-ja-circleci-webhook](https://user-images.githubusercontent.com/159403/158003470-6c5fdae4-5190-4e6c-ad36-c459948dd151.png)

2022-03-12 04:41 UTC, tatsuya6502 commented
レビュータスク

- [x] コードブロック（`listings/ch02-guessing-game-tutorial/`）の内容が、日本語コメントを除いて英語版と同じであることを確認する。
    - ```
      diff -u -r ../../listings/ch02-guessing-game-tutorial/ listings/ch02-guessing-game-tutorial/
      ```
- [ ] 和訳の変更点を確認する

2022-03-12 05:08 UTC, tatsuya6502 requested changes
ありがとうございます。何点かコメントしましたので、ご確認ください。

2022-03-12 05:08 UTC, tatsuya6502 commented on src/ch02-00-guessing-game-tutorial.md
> +{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/listing-02-01/src/main.rs:all}}
`listings/ch02-guessing-game-tutorial/listing-02-01/src/main.rs` に、古いコードブロックにある和訳を追加してください。

[こちら](https://github.com/rust-lang-ja/rust-by-example-ja/blob/master/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88) （rust-by-exampleのCONTRIBUTION）にあるように、ソースコードブロック中のコメントは、元の英文を残して次の行に訳してください。

2022-03-12 05:08 UTC, tatsuya6502 commented on src/ch02-00-guessing-game-tutorial.md
> +`0.8.3`という数字は、実際には`^0.9.3`の省略記法で、これは、「バージョン0.8.3と互換性のある公開APIを持つ0.9.0未満の任意のバージョン」を意味します。
```suggestion
`0.8.3`という数字は、実際には`^0.8.3`の省略記法で、これは、「バージョン0.8.3と互換性のある公開APIを持つ0.9.0未満の任意のバージョン」を意味します。
```

2022-03-12 05:08 UTC, tatsuya6502 commented on src/ch02-00-guessing-game-tutorial.md
> +    (レジストリを更新しています)
```suggestion
    Updating crates.io index
    (crates.ioインデックスを更新しています)
```

2022-03-12 05:08 UTC, tatsuya6502 commented on src/ch02-00-guessing-game-tutorial.md
> +{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/listing-02-03/src/main.rs:all}}
listings/ch02-guessing-game-tutorial/listing-02-03/src/main.rsに、古いコードブロックにある和訳（` //秘密の数字は次の通り: {}`）を追加してください。

2022-03-12 05:08 UTC, tatsuya6502 commented on src/ch02-00-guessing-game-tutorial.md
> +{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/listing-02-04/src/main.rs:here}}
listings/ch02-guessing-game-tutorial/listing-02-04/src/main.rsに、古いコードブロックにある和訳（`//小さすぎ！`、など）を追加してください。

2022-03-13 10:10 UTC, puripuri2100 commented on src/ch02-00-guessing-game-tutorial.md
> +{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/listing-02-04/src/main.rs:here}}
修正しました

2022-03-13 10:10 UTC, puripuri2100 commented on src/ch02-00-guessing-game-tutorial.md
> +{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/listing-02-03/src/main.rs:all}}
修正しました

2022-03-13 10:10 UTC, puripuri2100 commented on src/ch02-00-guessing-game-tutorial.md
> +    (レジストリを更新しています)
修正しました

2022-03-13 10:10 UTC, puripuri2100 commented on src/ch02-00-guessing-game-tutorial.md
> +`0.8.3`という数字は、実際には`^0.9.3`の省略記法で、これは、「バージョン0.8.3と互換性のある公開APIを持つ0.9.0未満の任意のバージョン」を意味します。
修正しました

2022-03-13 10:14 UTC, puripuri2100 commented on src/ch02-00-guessing-game-tutorial.md
> +{{#rustdoc_include ../listings/ch02-guessing-game-tutorial/listing-02-01/src/main.rs:all}}
修正しました

わかりました
以後そのように修正を反映させていきます

2022-03-13 10:47 UTC, tatsuya6502 approved these changes
ありがとうございます。レビューOKですのでマージします。

おつかれさまでした！

2022-03-13 10:48 UTC, merged