3章をupdateした
rust-lang-ja/book-ja pull request #194
Opened 2022-03-27 06:07 UTC by puripuri2100

- コードの更新
- コード表記をファイル参照の形に変更
- コードの変更に伴った説明の追加・修正

を行いました。

2022-04-24 15:13 UTC, tatsuya6502 requested changes
レビューが遅くなり申しわけありません。

古いコードブロックが残っている場所が2箇所あり、それぞれコメントしました。ご確認のうえ、古い方の削除をお願いします。

2022-04-24 15:13 UTC, tatsuya6502 commented on src/ch03-03-how-functions-work.md
>  ```rust
古いコードブロックを削除してください。（右の行番号で123から131まで）

2022-04-24 15:13 UTC, tatsuya6502 commented on src/ch03-05-control-flow.md
>  ```rust,ignore
古いコードブロックを削除してください。（右の行番号で384から390まで）

2022-05-15 03:55 UTC, puripuri2100 commented
大変遅くなり申し訳ありません
指摘されていた古いコードブロックが残っている箇所の削除をしました

2022-05-15 11:04 UTC, tatsuya6502 approved these changes
レビューOKですのでマージします。おつかれさまでした！

2022-05-15 11:04 UTC, merged