コードブロック内のコメントを修正
rust-lang-ja/book-ja pull request #205
Opened 2022-05-07 06:44 UTC by jmblog

2022-05-15 11:15 UTC, tatsuya6502 requested changes
誤字を修正していただきありがとうございました。一点コメントしましたのでご確認ください。

よろしくお願いします。

2022-05-15 11:15 UTC, tatsuya6502 commented on src/ch01-03-hello-cargo.md
> +$ ./target/debug/hello_cargo # Windowsでは .\target\debug\hello_cargo.exe
```suggestion
$ ./target/debug/hello_cargo # or .\target\debug\hello_cargo.exe on Windows
$                              # Windowsでは .\target\debug\hello_cargo.exe
```

すみませんが、英語の原文を元に戻してもらえないでしょうか？　原本（[rust-lang/book](https://github.com/rust-lang/book)）でこのコードブロックが更新されてないかを機械的にチェックするために、原文が必要になります。

2022-07-11 00:08 UTC, jmblog commented
@tatsuya6502 対応が遅くなってすみませんでした。修正いたしました。

2022-09-08 13:24 UTC, tatsuya6502 approved these changes
レビューが遅くなり申しわけありません。OKですのでマージします。

2022-09-08 13:24 UTC, merged