2018 edition chap7 翻訳
rust-lang-ja/book-ja pull request #64
Opened 2020-08-23 15:06 UTC by woodyZootopia

・英語の文ごとに日本語訳を改行しています。
・原文の意味を尊重しつつ、日本語としての読みやすさを重視した訳にしました。
長大ですが、レビューよろしくおねがいします。

----
以下は @tatsuya6502 による追記
Fixes: #49, #50, #51, #52, #53 and #54

2020-08-23 22:40 UTC, tatsuya6502 commented
レビュー用HTML: https://11-223145361-gh.circle-artifacts.com/0/docs/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html

2020-08-24 15:34 UTC, tatsuya6502 reviewed
日本語の流れが良くて、内容がスッと頭に入りますね。ありがとうございます。

まだレビューの途中ですが、今日のところは時間切れとなってしまいました。とりあえず、いまレビューした部分についてフィードバックします。（何点かコメントしました）

2020-08-24 15:34 UTC, tatsuya6502 commented on src/ch07-02-defining-modules-to-control-scope-and-privacy.md
> +後方部門とはシェフや料理人がキッチンで働き、皿が洗われ、マネージャが管理業務をする場所です。
皿が洗われ、
　↓
皿洗い係が片づけをし、（または、皿洗い係が食器を片づけ、）

2020-08-24 15:34 UTC, tatsuya6502 commented on src/ch07-00-managing-growing-projects-with-packages-crates-and-modules.md
> +関係した機能をまとめ、異なる特徴を持つコードを分割することにより、特定の機能を実装しているコードを見つけたり、機能を変更したりするためにどこを探せば良いのかを明確にすることができます。
明確にすることができます
　　↓
明確にできます

「することができます」は少し冗長な言い回しなので、あまり使わない方がいいでしょう。行為を強調したいときだけに使うのがお勧めです。

2020-08-24 15:34 UTC, tatsuya6502 commented on src/ch07-00-managing-growing-projects-with-packages-crates-and-modules.md
> +プロジェクトが大きくなるに連れて、これを複数のモジュールに、ついで複数のファイルに分割することで、プログラムを整理することができます。
プログラムを整理することができます
　　↓
プログラムを整理できます

2020-08-24 15:34 UTC, tatsuya6502 commented on src/ch07-00-managing-growing-projects-with-packages-crates-and-modules.md
> +機能をグループにまとめられることに加え、実装の詳細がカプセル化されることにより、コードをより高いレベルで再利用することができます：
機能をグループにまとめられることに加え、実装の詳細がカプセル化されることにより、コードをより高いレベルで再利用することができます。
　　↓
機能をグループにまとめることに加え、実装の詳細をカプセル化することで、コードをより高いレベルで再利用できるようになります。

2020-08-24 15:39 UTC, woodyZootopia commented on src/ch07-00-managing-growing-projects-with-packages-crates-and-modules.md
> +関係した機能をまとめ、異なる特徴を持つコードを分割することにより、特定の機能を実装しているコードを見つけたり、機能を変更したりするためにどこを探せば良いのかを明確にすることができます。
「することができます」は僕の癖みたいですね。多分この後でも頻出するので、気づいたら教えてください……。

2020-08-24 15:39 UTC, woodyZootopia commented
レビューありがとうございます。僕の方でも提出後に気づいたところコメントしていきます。

2020-08-24 15:41 UTC, woodyZootopia commented on src/ch07-02-defining-modules-to-control-scope-and-privacy.md
> +モジュールは要素の *プライバシー* も制御できます。プライバシーとは、要素がコードの外側で使える *(公開 public)* か、内部の実装の詳細であり外部では使えない *(非公開 private)* か、です。
「プライバシーとは、〜か、〜かのどちらなのかということです。」のほうが原文の意図を正確に伝えられる？
やや冗長かも？

2020-08-24 15:42 UTC, woodyZootopia commented on listings/ch07-managing-growing-projects/listing-07-09/src/lib.rs
> +    // 季節の野菜を知ることも修正することも許されていないので
野菜→フルーツ

2020-08-26 10:02 UTC, woodyZootopia commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +* *相対パス* は、`self`、`super`または今のモジュール内の指定子を使うことで、現在のモジュールからスタートします。
指定子→識別子

2020-08-26 10:03 UTC, woodyZootopia commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +絶対パスも相対パスも、その後に一つ以上の指定子がダブルコロン(`::`)で仕切られて続きます。
指定子→識別子

2020-08-26 10:41 UTC, tatsuya6502 commented
@woodyZootopia — なかなかレビューできなくてすみません。識別子やフルーツなど、ご自身で気づいて修正したい箇所があったら、レビューが終わるのを待たずに、2018_chap7_translate ブランチへ修正を直接コミットしていってください。

2020-08-26 11:37 UTC, woodyZootopia commented
@tatsuya6502 いえいえ、お時間ある時で大丈夫です！ありがとうございます！
修正は（どれをコミットしたかわからなくなりそうなので）レビューが終わった段階でまとめて行おうかと思っているのですがそれでも良いですか？

2020-08-26 11:51 UTC, tatsuya6502 commented
はい。もちろん、レビューが終わってからのまとめて修正でもOKです。

2020-08-30 07:31 UTC, tatsuya6502 commented on src/ch07-02-defining-modules-to-control-scope-and-privacy.md
> +モジュールを使うことで、関係する定義を一つにまとめ、どうして関係しているのかに名前をつけることができます。
[nits]
> モジュールを使うことで、関係する定義を一つにまとめ、どうして関係しているのかに名前をつけることができます。

意訳ですが、以下のような訳はどうでしょうか？

> モジュールを使うことで、関連する定義を一つにまとめ、関連する理由を名前で示せます。

2020-08-30 10:59 UTC, tatsuya6502 reviewed
ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md をレビューしました。

2020-08-30 10:59 UTC, tatsuya6502 commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +しかし、`pub`キーワードを使って要素を公開することで、子モジュールの内部部品を外部の祖先モジュールに公開することができます。
[nit]

要素を公開することで、 ...　祖先モジュールに公開することができます。
　　↓
要素を公開することで、 ...　祖先モジュールに見せられます。

「公開すること」が2回続いていたので、expose（直訳すると「露出させる」）は「見せる」にしてみました。

2020-08-30 10:59 UTC, tatsuya6502 commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +`add_to_waitlist`の宣言の前に`pub`キーワードを追加して、これも公開しましょう。
[nit]

`add_to_waitlist`の宣言の前に
　　↓
`add_to_waitlist`の定義の前に

- declaration/宣言
- definition/定義

2020-08-30 10:59 UTC, tatsuya6502 commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +相対パスについての議論も、最初のステップを除けば同じです。パスをクレートルートから始めるのではなくて、`front_of_house`から始めるのです。
相対パスについての議論も、最初のステップを除けば同じです。
　　↓
相対パスについても、最初のステップを除けば同じロジックになります。

ITの世界ではロジックという用語がよく使われるので、そのままロジックでいいかなと思いました。あるいは、「同じ理屈です」でもいいかもしれません。

2020-08-30 10:59 UTC, tatsuya6502 commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +`..`構文をファイルシステムパスの最初につけるのに似ています。
[nit]

`..`構文をファイルシステムパスの最初につけるのに似ています。
　　↓
ファイルシステムパスを`..`構文で始めるのに似ています。

2020-08-30 10:59 UTC, tatsuya6502 commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +構造体やenumも`pub`を使って公開するよう指定することができますが、追加の細目がいくつかあります。
[nit]

公開するよう指定することができますが
　　↓
公開するよう指定できますが

2020-08-30 10:59 UTC, tatsuya6502 commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +enumはヴァリアントが公開されてないとあまり便利ではないのですが、毎回enumのすべてのヴァリアントに`pub`をつけないといけないなんて面倒なので、enumのヴァリアントは標準で公開されるようになっているのです。
[nit]

`Appetizer`というenumを公開したので、... で使うことができます。
... `pub`をつけないといけないなんて面倒なので ...

　　↓

`Appetizer`というenumを公開したので、... から使えます。
... `pub`をつけるのは面倒なので ...

2020-08-31 13:34 UTC, tatsuya6502 requested changes
7章のレビュー、終わりました。お待たせしました。

[nits]（粗探し）マークの付いたコメントは、些細なものなので無視してもかまわないです。

2020-09-01 00:43 UTC, woodyZootopia commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +レストランの喩えを続けるなら、レストランの後方部門になったつもりでプライバシーのルールを考えてみてください。レストランの顧客にはそこで何が起こっているのかは非公開ですが、そこで働くオフィスマネージャには、レストランのことは何でも見えるし何でもできるのです。
the restaurant in which they operateなので、they (office managers) operate in the restaurantということになるかな、と思いこの訳にしました。

2020-09-01 00:54 UTC, woodyZootopia commented on src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
> +こうすることで、私達のライブラリを、ライブラリに取り組むプログラマにとっても、ライブラリを呼び出すプログラマにとっても、よく整理されたものとすることができます。
更に意訳して「ライブラリを開発する」としてみました。やりすぎですかね？

2020-09-01 00:59 UTC, woodyZootopia commented
@tatsuya6502 レビューありがとうございました！反映しましたので、お時間あるときにご確認お願いします。

2020-09-01 11:42 UTC, tatsuya6502 commented on src/ch07-03-paths-for-referring-to-an-item-in-the-module-tree.md
> +レストランの喩えを続けるなら、レストランの後方部門になったつもりでプライバシーのルールを考えてみてください。レストランの顧客にはそこで何が起こっているのかは非公開ですが、そこで働くオフィスマネージャには、レストランのことは何でも見えるし何でもできるのです。
「それを運営する」ですと、現場（レストラン）に居ないような雰囲気があるってことでしょうか。たしかに、それはあるかもしれませんね。ではこのまま「そこで働く」にしておきましょう。

2020-09-01 11:48 UTC, tatsuya6502 commented on src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
> +こうすることで、私達のライブラリを、ライブラリに取り組むプログラマにとっても、ライブラリを呼び出すプログラマにとっても、よく整理されたものとすることができます。
「ライブラリを開発する」で良いと思います。

2020-09-01 11:52 UTC, tatsuya6502 approved these changes
レビュー結果を反映していただき、ありがとうございました。良いと思いますので、マージします。

おつかれさまでした。

2020-09-01 11:53 UTC, merged