付録A,
rust-lang-ja/book-ja pull request #69
Opened 2020-08-27 20:58 UTC by woodyZootopia

2020-09-04 11:53 UTC, tatsuya6502 reviewed
まだレビューの途中です。

- [x] appendix-01-keywords.md
- [ ] appendix-04-useful-development-tools.md
- [ ] appendix-05-editions.md

2020-09-04 11:53 UTC, tatsuya6502 commented on src/appendix-01-keywords.md
> +このエラーは`match`というキーワードを関数の指定子としては使えないと示しています。
関数の指定子
　　↓
関数の識別子

2020-09-04 11:53 UTC, tatsuya6502 commented on src/appendix-01-keywords.md
> +生識別子を使えば、仮にそれが予約されたキーワードであろうとも、任意の単語を指定子として使えるようになります。
指定子として
　　↓
識別子として

2020-09-04 23:24 UTC, tatsuya6502 requested changes
レビューが終わりました。何点かコメントしましたのでご確認をお願いします。

[nit]は些細なものなので、無視しても構いません。

2020-09-04 23:24 UTC, tatsuya6502 commented on src/appendix-05-editions.md
> +2、3年ごとに、Rustチームは新しいRustの *edition* を作ります。
[nit]

新しいRustの *edition* を作ります。
　　↓
新しいRust *edition* を作ります。
　　または
Rustの新しい *edition* を作ります。

2020-09-04 23:24 UTC, tatsuya6502 commented on src/appendix-05-editions.md
> +* Rustユーザでない人にとっては、新しいeditionは、何かしら大きな達成がなされたことを示します。Rustに今一度目を向けてみても良いかもしれません。
[nit]

> Rustに今一度目を向けてみても良いかもしれません。

この文ですと、なんとなく読者に向かって語りかけているように感じます。実際には、Rustユーザでない人について述べているので、以下のようにするのはどうでしょうか？

> Rustには今一度目を向ける価値があると感じさせるかもしれません。

2020-09-05 01:14 UTC, woodyZootopia commented
レビューありがとうございます！すべて取り入れました。

2020-09-05 01:32 UTC, tatsuya6502 approved these changes
ありがとうございます。OKですのでマージします。

おつかれさまでした。

2020-09-05 01:32 UTC, merged