Ch10-02 翻訳
rust-lang-ja/book-ja pull request #71
Opened 2020-09-02 09:21 UTC by woodyZootopia

Fixes: #58 
元のファイルを差分アップデートする形になってるので、Files Changedはやや煩雑です。

2020-09-04 23:57 UTC, tatsuya6502 reviewed
まだレビューの途中です。（引数としてのトレイトの前までレビューしました）

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +bring the trait into their scope first. They would do so by specifying `use
[nit]

一応、"need to import" が "need to bring" に変わったことに対応させるなら、以下のようになるでしょうか？

まず、トレイトをスコープにインポートする必要があるでしょう。
　　↓
まず、トレイトをスコープに取り込む必要があるでしょう。

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +in Listing 10-12.
[nit]

":" から "." への変更に対応するなら、

リスト10-14は ... 方法を示しています:
　　↓
リスト10-14は ... 方法を示しています。

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +最早`NewsArticle`に直接`summarize`メソッドを定義してはいませんが、私達はデフォルト実装を提供しており、
[nit]

ついでに「最早」→「もはや」に変更してもらえると嬉しいです。（他のページにもあるかもしれませんが、それらもいずれ「もはや」に置き換えるでしょうから今は無視していいです）

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +{{#rustdoc_include ../listings/ch10-generic-types-traits-and-lifetimes/no-listing-01-calling-trait-method/src/main.rs:here}}
listingファイル*1の方に日本語のソースコードコメントを移植してください。

> // もちろん、ご存知かもしれないようにね、みなさん


*1: ../listings/ch10-generic-types-traits-and-lifetimes/no-listing-01-calling-trait-method/src/main.rs

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +{{#rustdoc_include ../listings/ch10-generic-types-traits-and-lifetimes/listing-10-14/src/lib.rs:here}}
listingファイルに日本語のソースコードコメントを移植してください。

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +{{#rustdoc_include ../listings/ch10-generic-types-traits-and-lifetimes/no-listing-02-calling-default-impl/src/main.rs:here}}
listingファイルに日本語のソースコードコメントを移植してください。

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +{{#rustdoc_include ../listings/ch10-generic-types-traits-and-lifetimes/no-listing-03-default-impl-calls-other-methods/src/lib.rs:here}}
listingファイルに日本語のソースコードコメントを移植してください。

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +{{#include ../listings/ch10-generic-types-traits-and-lifetimes/no-listing-07-fixing-listing-10-05/output.txt}}
listingファイルに日本語訳を移植してください。

2020-09-04 23:57 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +### トレイトを実装するような型を返す
> トレイトを実装するような型を返す

「ような」は推量の意味を含んでいるので、ちょっと紛らわしいかもしれません。以下の訳はどうでしょうか？

> トレイトを実装している型を返す

2020-09-04 23:57 UTC, tatsuya6502 commented on src/title-page.md
> +- 10章には、新しい`impl Trait`構文を説明するために「引数としてのトレイト」と「トレイトを実装するような型を返す」という新しい節があります。
「トレイトを実装するような型を返す」という訳について src/ch10-02-traits.md ファイルでコメントしました。そちらの訳を修正した場合は、こちらも修正してください。

2020-09-05 12:27 UTC, tatsuya6502 reviewed
まだレビューの途中です。（「複数のトレイト境界を`+`構文で指定する」の前まで見ました）

2020-09-05 12:27 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +トレイト境界と、コロンを挟んでジェネリックな型引数の宣言を書き、それを角カッコで囲っています。
> トレイト境界と、コロンを挟んでジェネリックな型引数の宣言を書き、それを角カッコで囲っています。

この説明ですと`<T: Summary>`を書く順番が分かりにくいかもしれません。`<Summary: T>` のようにも受け取れます。

原文の構造が分かりにくいのですが、commaで区切ると、おそらく “We place trait bounds, with the declaration of the generic type parameter, after a colon, and inside angle brackets." だと思います。直訳すると「私たちはトレイト境界を、ジェネリックな型引数の宣言と共に、コロンの後ろ、かつ、角カッコの中に置きます」

元の訳文の順番を入れ替えて、こんな感じにするのはどうでしょうか？

> 角カッコの中にジェネリックな型引数の宣言を書き、型引数の後ろにコロンを挟んでトレイト境界を置いています。

2020-09-05 12:27 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +引数である`item1`と`item2`の型としてジェネリックな型`T`を指定することにより、実際に関数に`item1`と`item2`として渡される変数の値は同じ具体的な型を持っていなくてはならないと制約しています。
[nit]

> 引数である`item1`と`item2`の型としてジェネリックな型`T`を指定することにより、実際に関数に`item1`と`item2`として渡される変数の値は同じ具体的な型を持っていなくてはならないと制約しています。

文が長いのと少し言葉が増えているようです（例：変数）

こんな感じはどうでしょうか？

> 引数`item1`と`item2`の型としてジェネリックな型`T`を指定しました。これにより関数に、`item1`と`item2`に実際に渡される値の具体的な型が同一である、という制約を与えています。

2020-09-05 23:46 UTC, tatsuya6502 reviewed
まだレビュー途中です。（トレイトを実装するような型を返すの前まで読みました）

2020-09-05 23:46 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +たとえば、`notify`が`summarize`メソッドに加えて`item`の画面出力形式（ディスプレイフォーマット）を使いたいとします。すなわち、`notify`の定義に`item`は`Display`と`Summary`の両方を実装していなくてはならないと指定したいとします。
[nit]

**最初の文**

たとえば、`notify`が`summarize`メソッドに加えて`item`の画面出力形式（ディスプレイフォーマット）を使いたいとします。
　　↓
たとえば、`notify`に`summarize`メソッドに加えて`item`の画面出力形式（ディスプレイフォーマット）を使わせたいとします。

`notify`が使いたい、のではなく、私たちが`notify`に使わせたい。

**2つ目の文**

接続詞がないので、最初の文と2つ目の文の関係が分かりにくいのですが、

1. Say we wanted （過去形）
2. we specify （現在系）

となっていることから、以下のような関係だと考えられます。

1. たとえば、○○したかったとします。
2. なら、△△することになります。

2つ目の文を以下のように変えるのはどうでしょうか？

すなわち、`notify`の定義に`item`は`Display`と`Summary`の両方を実装していなくてはならないと指定したいとします。
　　↓
その場合は、`notify`の定義に`item`は`Display`と`Summary`の両方を実装していなくてはならないと指定することになります。

2020-09-05 23:46 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +ジェネリック型に対しても`+`構文は使えます：
ジェネリック型に対しても`+`構文は使えます：
　　↓
`+`構文はジェネリック型につけたトレイト境界に対しても使えます：

2020-09-05 23:46 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +それぞれのジェネリック（な型）にそれぞれのトレイト境界があるので、複数のジェネリック型の引数をもつ関数は、関数名と引数リストの間に大量のトレイト境界に関する情報を含まないといけないかもしれません。これでは関数のシグネチャが読みにくくなってしまいます。
[nit]

平仮名を少し減らすと読みやすくなるかなと思いました。

たとえば、

それぞれのジェネリック（な型）にそれぞれのトレイト境界があるので、
　　↓
それぞれのジェネリック（な型）はそれ固有のトレイト境界をもつので、

含まないといけないかもしれません。
　　↓
含むかもしれません。

2020-09-06 11:32 UTC, tatsuya6502 requested changes
レビューしました。コメントを確認願います。

[nit]は些細なものなので無視しても大丈夫です。

2020-09-06 11:32 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +`PartialOrd`は初期化処理に含まれているので、これをスコープに導入する必要はありません。
> `PartialOrd`は初期化処理に含まれているので、

"in the prelude"ですが、元の訳が間違ってますね。[prelude](https://doc.rust-lang.org/std/prelude/index.html)はstdクレートにあるモジュールの名前で、自動的に`use`されます。

いま調べたところ、preludeについては既に [2章で説明されていました](https://github.com/rust-lang-ja/book-ja/blob/master-ja/src/ch02-00-guessing-game-tutorial.md#%E4%BA%88%E6%83%B3%E3%82%92%E5%87%A6%E7%90%86%E3%81%99%E3%82%8B)。

> デフォルトでは、preludeに存在するいくつかの型のみ使えます。

ですからここの訳も以下のようにするのがいいと思います。

`PartialOrd`は初期化処理に含まれているので、
　　↓
`PartialOrd`はpreludeに含まれているので、

2020-09-06 11:32 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +第4章の[スタックのみのデータ: コピー][stack-only-data-copy]節で議論したように、`i32`や`char`のようなサイズが既知の型は、
[nit]

細かくてすみませんが、この行の終わりの読点（、）をついでに削除してもらえると嬉しいです。

のようなサイズが既知の型は、
　　↓
のようなサイズが既知の型は

2020-09-06 11:32 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +動的型付け言語では、型が実装しない型のメソッドを呼び出せば、実行時 (runtime) にエラーが出るでしょう。
型が実装しない型のメソッドを呼び出せば
　　↓
その型に定義されていないメソッドを呼び出せば

----
用語統一：

他の章にもありそうですが、いまはここだけ直してもらえばOKです。

動的型付け言語
　　↓
動的型付き言語

2020-09-07 15:46 UTC, woodyZootopia commented
レビューありがとうございます！気が緩んできてしまったようで、ミスが多くてすみません。
レビューに対応する1つ目のコミットの後、前半部分の不自然な言葉遣いとかの修正が甘かったところを修正し、改行がなくて読みづらい部分を改行するコミットを出しました。細かな修正なので問題はないと思いますが、もしよろしければ確認お願いします。

2020-09-08 12:34 UTC, tatsuya6502 commented on src/ch10-02-traits.md
> +{{#rustdoc_include ../listings/ch10-generic-types-traits-and-lifetimes/no-listing-02-calling-default-impl/src/main.rs:here}}
メモ：`// 新しい記事が利用可能です！ {}` ほソースコード中ではなく、本文に記載。

2020-09-08 12:53 UTC, tatsuya6502 approved these changes
レビュー結果の反映と、不自然な言葉遣いなどの修正、ありがとうございました。良いと思います。ミスについては気にしないでください。翻訳作業が捗っていて、とても助かっています。

この内容でマージします。おつかれさまでした。

2020-09-08 12:53 UTC, merged