Chap-11-01 翻訳のアップデート
rust-lang-ja/book-ja pull request #72
Opened 2020-09-03 08:20 UTC by woodyZootopia

Fixes: #59

2020-09-09 11:14 UTC, woodyZootopia commented on src/ch11-01-writing-tests.md
> -<span class="filename">ファイル名: src/lib.rs</span>
この行を間違って消してしまっていますね。

2020-09-10 07:52 UTC, woodyZootopia commented on src/ch11-01-writing-tests.md
> -<span class="filename">ファイル名: src/lib.rs</span>
下のコミットで修正しました。

2020-09-13 01:15 UTC, tatsuya6502 requested changes
翻訳していただき、ありがとうございます。何点かコメントしましたので、ご確認ください。

2020-09-13 01:15 UTC, tatsuya6502 commented on src/ch11-01-writing-tests.md
> +`Result<T, E>` を返すようなテストを書くと、ハテナ演算子（訳注：`?`のこと）をテストの中で使えるようになります。
```
ハテナ演算子
　　↓
`?`演算子
```

他の章では`?`演算子で統一されているようです。（ハテナ演算子という呼びかたも面白いので会話などで使わせてもらうかもしれません）

2020-09-13 02:31 UTC, woodyZootopia commented
レビューありがとうございます。
頂いた指摘をすべて反映し、その周辺で気になったところを微修正しました。
また、title-page.mdとコンフリクトが発生していたので、現在のorigin/master-jaにリベースしました。
ご確認よろしくおねがいします。

2020-09-13 02:46 UTC, tatsuya6502 commented on src/title-page.md
> +<<<<<<< HEAD
この行を削除してください。（rebaseの際に入ってしまったのだと思います）

2020-09-13 04:24 UTC, tatsuya6502 approved these changes
レビュー内容を反映していただき、ありがとうございました。レビューOKですのでマージします。

おつかれさまでした！

2020-09-13 04:24 UTC, merged