Translate 19 06
rust-lang-ja/book-ja pull request #75
Opened 2020-09-05 02:38 UTC by woodyZootopia

Fixes: #60

procedural macroを「プロシージャルマクロ」と訳していましたが、意味がわかりにくい＆そもそも発音が違う（プロシージュラル）ので、とりあえず「手続き的マクロ」という訳で統一しています。
同様にdeclarative macroは「宣言的マクロ」と訳しました。

また、custom derive macroも、「カスタムのderiveマクロ」と訳しましたが、この訳はどうなんでしょうね……？「独自のderiveマクロ」とかでも良いかもしれません。

2020-09-13 03:58 UTC, tatsuya6502 reviewed
まだレビューの途中です。（「カスタムの`derive` マクロの書き方」の前まで読みました）

2020-09-13 03:58 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +各パターンに紐づいたコードは、マクロに渡されたコードを置き換えるコードです。これは全て、コンパイル時に起きます。
> 各パターンに紐づいたコードは、マクロに渡されたコードを置き換えるコードです。

- "when matched," に対応する句を追加してください。
- "is the code" が削除されたので、それも反映してください。

例：
各パターンに紐づいたコードは、それがマッチした時にマクロに渡されたコードを置き換えます。

2020-09-13 03:58 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +specifies that the pattern matches zero or more of whatever precedes the `*`.
> カンマに続く`*`は、パターンが`*`の前にあるもの0個以上にマッチすることを指定しています。

原文で"following the comma"が削除されていますので、それに対応する「カンマに続く」を削除してください。

"following the comma"が削除された理由は、説明しているコードの中に `*` が2回出てきて、1つ目の `,*` はカンマに続いているものの、2つ目の `)*` はそうなってないためだと思われます。

https://github.com/rust-lang-ja/book-ja/blob/master-ja/listings/ch19-advanced-features/listing-19-28/src/lib.rs

2020-09-13 03:58 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +手続き的マクロは、宣言的マクロがパターンマッチングとコードの他のコードでの置き換えをしていたのとは違い、
[nit]

> 手続き的マクロは、宣言的マクロがパターンマッチングとコードの他のコードでの置き換えをしていたのとは違い、

"replacing the code with other code" の the code はパターンにマッチしたコードを指しているのだと思います。それを踏まえると、以下のようにした方がわかりやすいかもしれません。

> 宣言的マクロがパターンマッチングを行い、マッチしたコードを他のコードで置き換えていたのとは違い、手続き的マクロは

2020-09-13 04:21 UTC, tatsuya6502 commented
> 以前の訳ではprocedural macroを「プロシージャルマクロ」と訳していましたが、意味がわかりにくい＆そもそも発音が違う（プロシージュラル）ので、とりあえず「手続き的マクロ」という訳で統一しています。
> 同様にdeclarative macroは「宣言的マクロ」と訳しました。

良いと思います。

> そもそも発音が違う

残念ながら、3D CGの業界などではプロシージャルという訳語で定着してしまっているようです。

個人的には「手続き的」「宣言的」という訳の方が好みです。

> また、custom derive macroを「カスタムのderiveマクロ」と訳しましたが、この訳はどうなんでしょうね……？「独自のderiveマクロ」とかでも良いかもしれません。

この本全体を見ると、customは基本的にカスタムと訳しているようですので、「カスタムのderiveマクロ」で大丈夫だと思います。

2020-09-14 16:06 UTC, tatsuya6502 reviewed
まだレビューの途中です。（修正後のch19-06-macros.mdの508行目まで見ました）

2020-09-14 16:06 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +リスト19-30のようなコードを書けるようにするクレートを記述します。
この行より3行上の行

プロシージャル
　　↓
手続き的

この他にも何ヶ所か「プロシージャル」が出てくるので、それらも「手続き的」に修正願います。

2020-09-15 14:41 UTC, tatsuya6502 reviewed
（764行目まで読みました）

2020-09-15 14:41 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +Rustに付随してくるので、*Cargo.toml*の依存に追加する必要はありませんでした。`proc_macro`クレートは私達のコードからRustのコードを読んだり操作したりするのを可能にするRustのAPIです。
> `proc_macro`クレートは私達のコードからRustのコードを読んだり操作したりするのを可能にするRustのAPIです。

- 「RustのAPI」のところの原文は"compiler's API"

例：
> `proc_macro`クレートはコンパイラのAPIで、私達のコードからRustのコードを読んだり操作したりすることを可能にします。

2020-09-15 14:41 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +ここで`parse`関数が失敗したら、`unwrap`を呼び出してパニックさせていることにお気付きかもしれません。
> ここで`parse`関数が失敗したら、`unwrap`を呼び出してパニックさせていることにお気付きかもしれません。

- "`hello_macro_derive` function" の訳が抜けている
- 「`parse`関数」ではなく、「`syn::parse`関数」
-  「失敗したら、`unwrap`を呼び出して」
     - 失敗したときだけ`unwrap`を呼び出すように読めるが、実際には常に`unwrap`を呼んでいる

以下のようにするのはどうでしょうか？

> ここで`unwrap`を呼び出すことで、`syn::parse`関数が失敗したときに`hello_macro_derive`関数をパニックさせていることに気付いたかもしれません。

2020-09-15 14:41 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +Listing 19-32の構造体を見ると、`impl_hello_macro`関数をListing 19-30のコードに実行したときに私達の得る`ident`は、`Pancakes`という値を持ったフィールド`ident`を持っているとわかります。
> `Pancakes`という値を持ったフィールド`ident`を持っている

- `Pancakes`のダブルクオーテーションがない。（正しくは`"Pancakes"`）
- 「...を持った ...を持っている」　可能なら「持つ」の繰り返しを避けたい
- "will have" なので「持っている（事実）」より「持つでしょう（推測）」の方が適切

例：
> フィールド`ident`の値として`"Pancakes"`を持つでしょう。

`Ident`構造体は常に`ident`フィールドを持つので、値の`"Pancakes"`の方を強調しました。

2020-09-22 09:08 UTC, tatsuya6502 requested changes
最後までレビューしました。時間がかかってしまい申しわけありません。

何点かコメントしました。[nits]は些細なものなので、無視してもかまいません。

2020-09-22 09:08 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +`proc-macro`クレートを使ってクレートを作り、あなたのほしいコードを生成してくれる関数を実装すればよいです！
> `proc-macro`クレートを使ってクレートを作り、

"the `proc-macro` crate type" の type が抜けているようです。以下のようにするのはどうでしょうか？

> `proc-macro`クレートタイプを使ってクレートを作り、

　　または

> クレートタイプとして`proc-macro`使ってクレートを作り、

2020-09-22 09:08 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +これらは、`macro_rules!`マクロのように、関数よりフレクシブルです。
フレクシブルです
　　↓
フレキシブルです
　または
柔軟性があります

2020-09-22 09:08 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +このマクロは、中に入れられたSQL文をパースし、それが構文的に正しいことを確かめます。これは`macro_rules!`マクロが可能なよりも遥かに複雑な処理です。
[nits]

`macro_rules!`マクロが可能なよりも
　　↓
`macro_rules!`マクロが可能とすることよりも
　または
`macro_rules!`マクロができることよりも

2020-09-23 03:25 UTC, woodyZootopia commented on src/ch19-06-macros.md
> +外側の関数（今回だと`hello_macro_derive`）のコードは、あなたが作ったりであったりするであろうほとんどすべての手続き的マクロのクレートで同じです。
「出会ったり」の変換しそこないですね、混乱させてしまってすみません。
「見る」が不自然かな、と感じたのでこのように訳してみましたが、やや砕けすぎている気もしますね。

2020-09-23 03:29 UTC, woodyZootopia commented on src/ch19-06-macros.md
> +外側の関数（今回だと`hello_macro_derive`）のコードは、あなたが作ったりであったりするであろうほとんどすべての手続き的マクロのクレートで同じです。
たつやさんの訳と折半して「見かけたり作ったりする」にしてみました。

2020-09-23 11:46 UTC, tatsuya6502 commented on src/ch19-06-macros.md
> +外側の関数（今回だと`hello_macro_derive`）のコードは、あなたが作ったりであったりするであろうほとんどすべての手続き的マクロのクレートで同じです。
> 「出会ったり」の変換しそこない

ああ、そういうことでしたか。なるほどー

2020-09-23 12:03 UTC, tatsuya6502 reviewed
レビュー結果の対応をしていただき、ありがとうございました。

細かくてすみませんが、何点か対応漏れ（？）があるようです。以下のコメントについて、ご確認をお願いします。

1. listingsにあるファイルへ、日本語のソースコードコメントを移植する。（[コメント](https://github.com/rust-lang-ja/book-ja/pull/75#discussion_r488045602)）
2. ch19-06-macros.mdの中にまだ何ヶ所か「プロシージャル」が残っているので、「手続き的」に変更する。（[コメント](https://github.com/rust-lang-ja/book-ja/pull/75#discussion_r488047048)）
3. "compiler's API"が「RustのAPI」と訳されているので、「コンパイラのAPI」に修正する。（[コメント](https://github.com/rust-lang-ja/book-ja/pull/75#discussion_r488691717)）

2020-09-23 20:39 UTC, woodyZootopia commented
うわああガバガバですみません……。次から気をつけます
これで多分大丈夫だと思うのですが、チェックお願いします

2020-09-23 23:44 UTC, tatsuya6502 approved these changes
ありがとうございます。レビューOKですのでマージします。

おつかれさまでした！

2020-09-23 23:44 UTC, merged