Update 01-01
rust-lang-ja/book-ja pull request #96
Opened 2020-09-27 13:38 UTC by woodyZootopia

Fixes: #95

2020-09-27 13:40 UTC, woodyZootopia commented on src/ch01-01-installation.md
> +どのworkloadsをインストールするかと質問されたときは、"C++ build tools"が選択されており、Windows 10 SDKとEnglish lanugage packが含まれていることを確かめてください。
WIndowsを持っていないのでここはよくわからなかったのですが、日本語話者はEnglish language packじゃなくて日本語の対応する何かを入れたほうが良いのかもしれないですね。

2020-09-29 08:46 UTC, woodyZootopia commented on src/ch01-01-installation.md
> +どのworkloadsをインストールするかと質問されたときは、"C++ build tools"が選択されており、Windows 10 SDKとEnglish lanugage packが含まれていることを確かめてください。
slack-jp、#devtools チャンネル上で出された、 @tatsuya6502 さんによる翻訳案：

>どのワークロードをインストールするかと質問されたときは、「C++ build tools」が選択されており、Windows 10 SDKと英語の言語パックが含まれていることを確かめてください。
> >訳注：Windowsの言語を日本語にしている場合は言語パックのところで「日本語」が選択されており、そのままの設定でインストールしても基本的に問題ないはずです。しかし、サードパーティーのツールやライブラリの中には英語の言語パックを必要とするものがあるため、「日本語」に加えて「英語」も選択することをお勧めします。

2020-10-11 09:25 UTC, tatsuya6502 requested changes
レビューしました。遅くなってすみません。

和訳の内容について、特に気になるとことはありませんでした。Windows language packのところは、Slackでの案をベースにして、訳注を追加してください。

2020-10-11 10:18 UTC, woodyZootopia commented
訳注を追加し、少しだけ勧誘文を追記しました。

2020-10-11 10:22 UTC, tatsuya6502 approved these changes
ありがとうございます。レビューOKですのでマージします。

おつかれさまでした！

2020-10-11 10:22 UTC, merged