Update 04-03
rust-lang-ja/book-ja pull request #97
Opened 2020-09-28 06:38 UTC by woodyZootopia

Fixes: #84

2021-04-04 12:38 UTC, tatsuya6502 requested changes
レビューまで何ヶ月もお待たせしてしまい、申しわけありませんでした。

訳文については特に気になった点はなかったのですが、誤って削除された段落があるようなので、それらについてコメントしました。（もしかしたらmdbook-transcheckの誤動作なのかなと思いました）　ご確認ください。

2021-04-04 12:38 UTC, tatsuya6502 commented on src/ch04-03-slices.md
> -
この段落が誤って削除されてしまったようです。復活していただけますか？

2021-04-04 12:38 UTC, tatsuya6502 commented on src/ch04-03-slices.md
> -
この段落も消えてしまったようです。復活をお願いします。（mdbook-transcheckの誤動作でしょうか？）

2021-05-20 03:25 UTC, woodyZootopia commented
確認ありがとうございます！修正しました。

2021-05-24 12:37 UTC, tatsuya6502 approved these changes
ありがとうございます。レビューOKですのでマージします。

おつかれさまでした！

2021-05-24 12:44 UTC, merged